name: Prometheus Rules

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  promtool:
    uses: umatare5/common/.github/workflows/promtool.yml@ec6477148fb47ffc8b34a89dfdc2ec725a82863a # v0.18.0
    with:
      promtool_version: "3.14.0"
      rule_files: |
        examples/prometheus_record_rules.yml
        examples/prometheus_alert_rules.yml
      test_files: |
        examples/prometheus_record_rules_test.yml
        examples/prometheus_alert_rules_test.yml
      config_files: |
        examples/prometheus.yml
      lint: "all"
