name: Prometheus Rules

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  promtool:
    uses: umatare5/common/.github/workflows/promtool.yml@8044b3c0ce0dce6411ec179c3ec0e675219c117f # v0.21.0
    with:
      promtool_version: "3.14.0"
      rule_files: |
        examples/prometheus_record_rules.yml
        examples/prometheus_alert_rules.yml
      test_files: |
        examples/prometheus_record_rules_test.yml
        examples/prometheus_alert_rules_test.yml
      config_files: |
        examples/prometheus.yml
      lint: "all"
